# Blacklayer configuration

USE_INPUT_ACTIVITY=false

run_blacklayer=true
run_lock=false
run_sleep=false

BLACKLAYER_DELAY=4
EVENT_POLL_INTERVAL=2
LOCK_DELAY=17
SLEEP_DELAY=7

LOCK_COMMAND=hyprlock
SLEEP_COMMAND='systemctl suspend'

resource=
source=/home/bob/.config/blacklayer/clock-widget.py

WAYLAND_DISPLAY=wayland-1

# HYPRLAND_INSTANCE_SIGNATURE=

dark_mode=true
