# Blacklayer configuration

USE_INPUT_ACTIVITY=false

run_blacklayer=true
run_lock=false
run_sleep=false

BLACKLAYER_DELAY=10
EVENT_POLL_INTERVAL=3
LOCK_DELAY=15
SLEEP_DELAY=10

LOCK_COMMAND=hyprlock
SLEEP_COMMAND='systemctl suspend'

resource=/home/bob/Resimler/wallpapers/FM7o.gif

WAYLAND_DISPLAY=wayland-1

# HYPRLAND_INSTANCE_SIGNATURE=

dark_mode=true
