# Blacklayer configuration

USE_INPUT_ACTIVITY=true

run_blacklayer=true
run_lock=true
run_sleep=false

BLACKLAYER_DELAY=10
EVENT_POLL_INTERVAL=3
LOCK_DELAY=10
SLEEP_DELAY=20

LOCK_COMMAND=hyprlock
SLEEP_COMMAND=systemctl suspend

resource=/home/bob/Resimler/wallpapers/KNGq.gif

WAYLAND_DISPLAY=wayland-1

# HYPRLAND_INSTANCE_SIGNATURE=

dark_mode=true
